
# Tomcat Server
server:
  port: 8080
  error.include-stacktrace: always

# Logger  
logging.level:
  web: DEBUG
  '[com.simplilearn.spring]': DEBUG

spring:
# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: rootroot
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        '[format_sql]': true
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      
---

# Docker Host DB Profile
spring:
  config:
    activate.on-profile: docker-host
# Database Settings
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/mydb  
    
---
# Docker Container DB Profile
spring:
  config:
    activate.on-profile: docker-container
# Database Settings
  datasource:
    url: jdbc:mysql://mydb:3306/mydb
    username: root
    password: root 